sudo: true
language: python
python:
  - "2.7"

compiler: gcc

env:
  global: 
  - DJANGO_SETTINGS_MODULE="cloudcv17.settings"
  # Caffe
  - WITH_CUDA=false
  - WITH_CMAKE=true
  - TOOLS_DIR="$HOME/tools"
  - WITH_IO=true

cache:
  pip: true
  custom_install: true
  apt: true
  directories:
  - $TOOLS_DIR/opencv
  - $TOOLS_DIR/tensorflow

before_install:
  - export NUM_THREADS=4
  - export SCRIPTS=./scripts/travis
  - source $SCRIPTS/defaults.sh
  - sudo $SCRIPTS/install_caffe.sh
  - sudo $SCRIPTS/install_tensorflow.sh

install:
  - git clone https://github.com/Cloud-CV/IDE.git
  - git submodule init
  - git submodule update
  - pip install -r requirements.txt
  - npm install
#  - $SCRIPTS/install-opencv.sh
  # - sudo $SCRIPTS/travis_install_caffe.sh

before_script:
  # - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib:/usr/local/cuda/lib64:$CONDA_DIR/lib
  # - export PATH=$CONDA_DIR/bin:$PATH
  # - if ! $WITH_CMAKE; then $SCRIPTS/travis_setup_makefile_config.sh; fi
  # - $SCRIPTS/travis_setup_and_build_caffe.sh
  # - export PYTHONPATH=$PYTHONPATH:$TOOLS_DIR/caffe/python

script:
  # - flake8 ./

after_success:
  - echo "done"

# after_failure:
#   - rm -rf $CONDA_DIR
#   - rm -rf $TOOLS_DIR/opencv
#   - echo "failure"

notifications:
  email:
  on_success: change
  on_failure: always
